spring:
    application:
        name: list
    datasource:
        url: jdbc:mariadb://localhost:3306/shopping
        username: shopping
        password: shopping
        driver-class-name: org.mariadb.jdbc.Driver
    flyway:
        enabled: true
        locations: classpath:db/migration
        baseline-on-migrate: true
